// <auto-generated />
using System;
using FinancesTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancesTracker.Migrations
{
    [DbContext(typeof(FinancesTrackerDbContext))]
    [Migration("20260104175527_InitialialMigration")]
    partial class InitialialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancesTracker.Shared.Models.cAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CntAccountType")
                        .HasColumnType("integer")
                        .HasColumnName("cnt_account_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PLN")
                        .HasColumnName("currency");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initial_balance");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Account_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Account_Name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dochód"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jedzenie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rozrywka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zdrowie"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dom i mieszkanie"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ubrania"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Edukacja"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Oszczędności"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Inne wydatki"
                        });
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keyword");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategory_id");

                    b.HasKey("Id")
                        .HasName("pk_category_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_rules_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CategoryRule_IsActive");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("IX_CategoryRule_Keyword");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_category_rules_subcategory_id");

                    b.ToTable("category_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "wynagrodzenie",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "pensja",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "biedronka",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "żabka",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "mcdonald",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "kfc",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "orlen",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "shell",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "netflix",
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "spotify",
                            SubcategoryId = 14
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "apteka",
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 10, 18, 5, 22, 37, 396, DateTimeKind.Utc),
                            IsActive = true,
                            Keyword = "leki",
                            SubcategoryId = 17
                        });
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subcategories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_subcategories_category_id");

                    b.ToTable("subcategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Wynagrodzenie"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Premia"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Freelance"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Inne dochody"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Zakupy spożywcze"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Restauracje"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Fast food"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Kawa i napoje"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Paliwo"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Komunikacja publiczna"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Taxi/Uber"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Serwis samochodu"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Name = "Kino"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "Subskrypcje"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Name = "Gry"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Name = "Leki"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Name = "Lekarz"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Name = "Dentysta"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Name = "Gimnastyka"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Name = "Czynsz"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Name = "Prąd"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Name = "Gaz"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Name = "Meble"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Name = "Odzież"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            Name = "Obuwie"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            Name = "Kursy"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Name = "Książki"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            Name = "Lokata"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 9,
                            Name = "Inwestycje"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 10,
                            Name = "Prezenty"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 10,
                            Name = "Różne"
                        });
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsInsignificant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_insignificant");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer")
                        .HasColumnName("month_number");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategory_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Transaction_AccountId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Transaction_CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Transaction_Date");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_transactions_subcategory_id");

                    b.HasIndex("Year", "MonthNumber")
                        .HasDatabaseName("IX_Transaction_Year_Month");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategoryRule", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cCategory", "Category")
                        .WithMany("CategoryRules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_categories_category_id");

                    b.HasOne("FinancesTracker.Shared.Models.cSubcategory", "Subcategory")
                        .WithMany("CategoryRules")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_subcategories_subcategory_id");

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cSubcategory", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cCategory", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subcategories_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cTransaction", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("FinancesTracker.Shared.Models.cCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("FinancesTracker.Shared.Models.cSubcategory", "Subcategory")
                        .WithMany("Transactions")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_subcategories_subcategory_id");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategory", b =>
                {
                    b.Navigation("CategoryRules");

                    b.Navigation("Subcategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cSubcategory", b =>
                {
                    b.Navigation("CategoryRules");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
