// <auto-generated />
using System;
using FinancesTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancesTracker.Migrations
{
    [DbContext(typeof(FinancesTrackerDbContext))]
    partial class FinancesTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancesTracker.Shared.Models.cAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bankname");

                    b.Property<int>("CntAccountType")
                        .HasColumnType("integer")
                        .HasColumnName("cntaccounttype");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PLN")
                        .HasColumnName("currency");

                    b.Property<string>("ImportIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("importidentifier");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initialbalance");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Account_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Account_Name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cAccountRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keyword");

                    b.HasKey("Id")
                        .HasName("pk_account_rules");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_rules_account_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AccountRule_IsActive");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("IX_AccountRule_Keyword");

                    b.ToTable("account_rules", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keyword");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoryid");

                    b.HasKey("Id")
                        .HasName("pk_category_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_rules_category_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CategoryRule_IsActive");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("IX_CategoryRule_Keyword");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_category_rules_subcategory_id");

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subcategories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_subcategories_category_id");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsInsignificant")
                        .HasColumnType("boolean")
                        .HasColumnName("isinsignificant");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("istransfer");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer")
                        .HasColumnName("monthnumber");

                    b.Property<int?>("RelatedTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("relatedtransactionid");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoryid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_Transaction_AccountId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Transaction_CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Transaction_Date");

                    b.HasIndex("RelatedTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_related_transaction_id");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_transactions_subcategory_id");

                    b.HasIndex("Year", "MonthNumber")
                        .HasDatabaseName("IX_Transaction_Year_Month");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cAccountRule", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cAccount", "Account")
                        .WithMany("AccountRules")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_rules_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategoryRule", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cCategory", "Category")
                        .WithMany("CategoryRules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_categories_category_id");

                    b.HasOne("FinancesTracker.Shared.Models.cSubcategory", "Subcategory")
                        .WithMany("CategoryRules")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_subcategories_subcategory_id");

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cSubcategory", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cCategory", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subcategories_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cTransaction", b =>
                {
                    b.HasOne("FinancesTracker.Shared.Models.cAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("FinancesTracker.Shared.Models.cCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("FinancesTracker.Shared.Models.cTransaction", "RelatedTransaction")
                        .WithOne()
                        .HasForeignKey("FinancesTracker.Shared.Models.cTransaction", "RelatedTransactionId")
                        .HasConstraintName("fk_transactions_transactions_related_transaction_id");

                    b.HasOne("FinancesTracker.Shared.Models.cSubcategory", "Subcategory")
                        .WithMany("Transactions")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_subcategories_subcategory_id");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("RelatedTransaction");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cAccount", b =>
                {
                    b.Navigation("AccountRules");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cCategory", b =>
                {
                    b.Navigation("CategoryRules");

                    b.Navigation("Subcategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancesTracker.Shared.Models.cSubcategory", b =>
                {
                    b.Navigation("CategoryRules");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
